/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as TestRouteImport } from './routes/test';
import { Route as AboutRouteImport } from './routes/about';
import { Route as IndexRouteImport } from './routes/index';
import { Route as DotwellKnownAgentCardDotjsonRouteImport } from './routes/[.]well-known/agent-card[.]json';
import { Route as ApiAgentManifestRouteImport } from './routes/api/agent/manifest';
import { Route as ApiAgentHealthRouteImport } from './routes/api/agent/health';
import { Route as ApiAgentEntrypointsRouteImport } from './routes/api/agent/entrypoints';
import { Route as ApiAgentEntrypointsKeyStreamRouteImport } from './routes/api/agent/entrypoints/$key/stream';
import { Route as ApiAgentEntrypointsKeyInvokeRouteImport } from './routes/api/agent/entrypoints/$key/invoke';

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const DotwellKnownAgentCardDotjsonRoute =
  DotwellKnownAgentCardDotjsonRouteImport.update({
    id: '/.well-known/agent-card.json',
    path: '/.well-known/agent-card.json',
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiAgentManifestRoute = ApiAgentManifestRouteImport.update({
  id: '/api/agent/manifest',
  path: '/api/agent/manifest',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAgentHealthRoute = ApiAgentHealthRouteImport.update({
  id: '/api/agent/health',
  path: '/api/agent/health',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAgentEntrypointsRoute = ApiAgentEntrypointsRouteImport.update({
  id: '/api/agent/entrypoints',
  path: '/api/agent/entrypoints',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAgentEntrypointsKeyStreamRoute =
  ApiAgentEntrypointsKeyStreamRouteImport.update({
    id: '/$key/stream',
    path: '/$key/stream',
    getParentRoute: () => ApiAgentEntrypointsRoute,
  } as any);
const ApiAgentEntrypointsKeyInvokeRoute =
  ApiAgentEntrypointsKeyInvokeRouteImport.update({
    id: '/$key/invoke',
    path: '/$key/invoke',
    getParentRoute: () => ApiAgentEntrypointsRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/test': typeof TestRoute;
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute;
  '/api/agent/entrypoints': typeof ApiAgentEntrypointsRouteWithChildren;
  '/api/agent/health': typeof ApiAgentHealthRoute;
  '/api/agent/manifest': typeof ApiAgentManifestRoute;
  '/api/agent/entrypoints/$key/invoke': typeof ApiAgentEntrypointsKeyInvokeRoute;
  '/api/agent/entrypoints/$key/stream': typeof ApiAgentEntrypointsKeyStreamRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/test': typeof TestRoute;
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute;
  '/api/agent/entrypoints': typeof ApiAgentEntrypointsRouteWithChildren;
  '/api/agent/health': typeof ApiAgentHealthRoute;
  '/api/agent/manifest': typeof ApiAgentManifestRoute;
  '/api/agent/entrypoints/$key/invoke': typeof ApiAgentEntrypointsKeyInvokeRoute;
  '/api/agent/entrypoints/$key/stream': typeof ApiAgentEntrypointsKeyStreamRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/test': typeof TestRoute;
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute;
  '/api/agent/entrypoints': typeof ApiAgentEntrypointsRouteWithChildren;
  '/api/agent/health': typeof ApiAgentHealthRoute;
  '/api/agent/manifest': typeof ApiAgentManifestRoute;
  '/api/agent/entrypoints/$key/invoke': typeof ApiAgentEntrypointsKeyInvokeRoute;
  '/api/agent/entrypoints/$key/stream': typeof ApiAgentEntrypointsKeyStreamRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/about'
    | '/test'
    | '/.well-known/agent-card.json'
    | '/api/agent/entrypoints'
    | '/api/agent/health'
    | '/api/agent/manifest'
    | '/api/agent/entrypoints/$key/invoke'
    | '/api/agent/entrypoints/$key/stream';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/about'
    | '/test'
    | '/.well-known/agent-card.json'
    | '/api/agent/entrypoints'
    | '/api/agent/health'
    | '/api/agent/manifest'
    | '/api/agent/entrypoints/$key/invoke'
    | '/api/agent/entrypoints/$key/stream';
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/test'
    | '/.well-known/agent-card.json'
    | '/api/agent/entrypoints'
    | '/api/agent/health'
    | '/api/agent/manifest'
    | '/api/agent/entrypoints/$key/invoke'
    | '/api/agent/entrypoints/$key/stream';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  TestRoute: typeof TestRoute;
  DotwellKnownAgentCardDotjsonRoute: typeof DotwellKnownAgentCardDotjsonRoute;
  ApiAgentEntrypointsRoute: typeof ApiAgentEntrypointsRouteWithChildren;
  ApiAgentHealthRoute: typeof ApiAgentHealthRoute;
  ApiAgentManifestRoute: typeof ApiAgentManifestRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test';
      path: '/test';
      fullPath: '/test';
      preLoaderRoute: typeof TestRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/.well-known/agent-card.json': {
      id: '/.well-known/agent-card.json';
      path: '/.well-known/agent-card.json';
      fullPath: '/.well-known/agent-card.json';
      preLoaderRoute: typeof DotwellKnownAgentCardDotjsonRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/agent/manifest': {
      id: '/api/agent/manifest';
      path: '/api/agent/manifest';
      fullPath: '/api/agent/manifest';
      preLoaderRoute: typeof ApiAgentManifestRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/agent/health': {
      id: '/api/agent/health';
      path: '/api/agent/health';
      fullPath: '/api/agent/health';
      preLoaderRoute: typeof ApiAgentHealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/agent/entrypoints': {
      id: '/api/agent/entrypoints';
      path: '/api/agent/entrypoints';
      fullPath: '/api/agent/entrypoints';
      preLoaderRoute: typeof ApiAgentEntrypointsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/agent/entrypoints/$key/stream': {
      id: '/api/agent/entrypoints/$key/stream';
      path: '/$key/stream';
      fullPath: '/api/agent/entrypoints/$key/stream';
      preLoaderRoute: typeof ApiAgentEntrypointsKeyStreamRouteImport;
      parentRoute: typeof ApiAgentEntrypointsRoute;
    };
    '/api/agent/entrypoints/$key/invoke': {
      id: '/api/agent/entrypoints/$key/invoke';
      path: '/$key/invoke';
      fullPath: '/api/agent/entrypoints/$key/invoke';
      preLoaderRoute: typeof ApiAgentEntrypointsKeyInvokeRouteImport;
      parentRoute: typeof ApiAgentEntrypointsRoute;
    };
  }
}

interface ApiAgentEntrypointsRouteChildren {
  ApiAgentEntrypointsKeyInvokeRoute: typeof ApiAgentEntrypointsKeyInvokeRoute;
  ApiAgentEntrypointsKeyStreamRoute: typeof ApiAgentEntrypointsKeyStreamRoute;
}

const ApiAgentEntrypointsRouteChildren: ApiAgentEntrypointsRouteChildren = {
  ApiAgentEntrypointsKeyInvokeRoute: ApiAgentEntrypointsKeyInvokeRoute,
  ApiAgentEntrypointsKeyStreamRoute: ApiAgentEntrypointsKeyStreamRoute,
};

const ApiAgentEntrypointsRouteWithChildren =
  ApiAgentEntrypointsRoute._addFileChildren(ApiAgentEntrypointsRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  TestRoute: TestRoute,
  DotwellKnownAgentCardDotjsonRoute: DotwellKnownAgentCardDotjsonRoute,
  ApiAgentEntrypointsRoute: ApiAgentEntrypointsRouteWithChildren,
  ApiAgentHealthRoute: ApiAgentHealthRoute,
  ApiAgentManifestRoute: ApiAgentManifestRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
